import type { Achievement, AchievementType } from '@shared/types'

const TYPE_LABEL: Record<AchievementType, string> = {
  academic: 'Education',
  professional: 'Professional Experience',
  certification: 'Certifications',
  training: 'Training',
  award: 'Awards',
  project: 'Projects',
  other: 'Other'
}

const TYPE_ORDER: AchievementType[] = [
  'professional',
  'academic',
  'certification',
  'training',
  'project',
  'award',
  'other'
]

function esc(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function fmt(d?: string): string {
  if (!d) return ''
  const date = new Date(d.length <= 10 ? d + 'T00:00:00' : d)
  if (Number.isNaN(date.getTime())) return d
  return date.toLocaleDateString('en-GB', { month: 'short', year: 'numeric' })
}

export function buildCvHtml(name: string, achievements: Achievement[]): string {
  const displayName = name && name.trim() ? name.trim() : 'My'
  const title = displayName.endsWith('s') ? `${displayName}'` : `${displayName}`
  const generated = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' })

  const allSkills = Array.from(new Set(achievements.flatMap((a) => a.skills ?? []))).slice(0, 30)

  const sections = TYPE_ORDER.map((type) => {
    const items = achievements
      .filter((a) => a.type === type)
      .sort((a, b) => (b.date || '').localeCompare(a.date || ''))
    if (!items.length) return ''
    const rows = items
      .map((a) => {
        const dates = a.endDate ? `${fmt(a.date)} – ${fmt(a.endDate)}` : fmt(a.date)
        const skills =
          a.skills && a.skills.length
            ? `<div class="skills">${a.skills.map((s) => `<span class="tag">${esc(s)}</span>`).join('')}</div>`
            : ''
        const org = a.organization ? `<span class="org">${esc(a.organization)}</span>` : ''
        const desc = a.description ? `<p class="desc">${esc(a.description)}</p>` : ''
        const link = a.link ? `<a class="link" href="${esc(a.link)}">${esc(a.link)}</a>` : ''
        return `
          <div class="item">
            <div class="item-head">
              <div>
                <span class="item-title">${esc(a.title)}</span>
                ${org ? `<span class="dot">·</span>${org}` : ''}
              </div>
              <span class="dates">${dates}</span>
            </div>
            ${desc}
            ${link}
            ${skills}
          </div>`
      })
      .join('')
    return `<section><h2>${TYPE_LABEL[type]}</h2>${rows}</section>`
  }).join('')

  const skillsBlock = allSkills.length
    ? `<section><h2>Skills</h2><div class="skills">${allSkills
        .map((s) => `<span class="tag">${esc(s)}</span>`)
        .join('')}</div></section>`
    : ''

  return `<!doctype html>
<html><head><meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1f2733; margin: 0; padding: 40px 48px; font-size: 13px; line-height: 1.5; }
  header { border-bottom: 3px solid #5aa84f; padding-bottom: 14px; margin-bottom: 22px; }
  h1 { margin: 0; font-size: 30px; color: #15391f; letter-spacing: -0.5px; }
  .subtitle { color: #5aa84f; font-weight: 600; font-size: 13px; margin-top: 2px; text-transform: uppercase; letter-spacing: 1px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #458a3c; border-bottom: 1px solid #dfe6df; padding-bottom: 4px; margin: 22px 0 12px; }
  .item { margin-bottom: 14px; page-break-inside: avoid; }
  .item-head { display: flex; justify-content: space-between; align-items: baseline; gap: 12px; }
  .item-title { font-weight: 700; color: #15391f; font-size: 14px; }
  .org { color: #3a455e; font-weight: 600; }
  .dot { color: #aab; margin: 0 6px; }
  .dates { color: #6b7689; font-size: 12px; white-space: nowrap; }
  .desc { margin: 4px 0 6px; color: #36404f; }
  .link { color: #369ad1; font-size: 12px; text-decoration: none; }
  .skills { margin-top: 6px; }
  .tag { display: inline-block; background: #eef5ec; color: #3f7a36; border: 1px solid #d7e7d2; border-radius: 10px; padding: 1px 9px; font-size: 11px; margin: 0 5px 5px 0; }
  footer { margin-top: 30px; padding-top: 10px; border-top: 1px solid #e5e9e5; color: #9aa3b2; font-size: 10px; text-align: center; }
</style></head>
<body>
  <header>
    <h1>${esc(title)} CV</h1>
    <div class="subtitle">Curriculum Vitae</div>
  </header>
  ${sections || '<p style="color:#9aa3b2">No achievements recorded yet.</p>'}
  ${skillsBlock}
  <footer>Generated by LifeHQ · ${generated}</footer>
</body></html>`
}
